kind: Deployment
apiVersion: apps/v1
metadata:
  name: uhd-mcp
  namespace: your-namespace
  annotations:
    deployment.kubernetes.io/revision: '18'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uhd-mcp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uhd-mcp
      annotations:
        cpu-load-balancing.crio.io: disable
        cpu-quota.crio.io: disable
        irq-load-balancing.crio.io: disable
        k8s.v1.cni.cncf.io/networks: your-sriov-network
    spec:
      containers:
        - resources:
            limits:
              openshift.io/sriovnet_connectx_6: '1'
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - ./start.sh
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MCP_SHARED_DATA_DIR
              value: "/app/uhd-mcp/shared-data-layer"
            - name: PAT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-pat
                  key: token
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'REPLACE_ME/mcp-uhd:latest'
          volumeMounts:
            - name: mcp-shared-data-layer-volume
              mountPath: /app/uhd-mcp/shared-data-layer
      volumes:
        - name: mcp-shared-data-layer-volume
          persistentVolumeClaim:
            claimName: mcp-shared-data-layer-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      schedulerName: default-scheduler